package sop_corba;


/**
* sop_corba/ControladorCancionIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 10 de agosto de 2022 19H40' CDT
*/

public interface ControladorCancionIntOperations 
{
  boolean registrarCancion (sop_corba.ControladorCancionIntPackage.CancionDTO objCancion);
  sop_corba.ControladorCancionIntPackage.CancionDTO[] listarCanciones ();
} // interface ControladorCancionIntOperations
