package sop_corba.ControladorCancionIntPackage;


/**
* sop_corba/ControladorCancionIntPackage/ListaCancionesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 10 de agosto de 2022 19H40' CDT
*/

public final class ListaCancionesHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ControladorCancionIntPackage.CancionDTO value[] = null;

  public ListaCancionesHolder ()
  {
  }

  public ListaCancionesHolder (sop_corba.ControladorCancionIntPackage.CancionDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ControladorCancionIntPackage.ListaCancionesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ControladorCancionIntPackage.ListaCancionesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ControladorCancionIntPackage.ListaCancionesHelper.type ();
  }

}
