package sop_corba.ControladorCancionIntPackage;


/**
* sop_corba/ControladorCancionIntPackage/CancionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 8 de agosto de 2022 19H40' CDT
*/

public final class CancionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String artista = null;
  public String titulo = null;
  public String tipo = null;
  public int tamKB = (int)0;
  public byte audio[] = null;

  public CancionDTO ()
  {
  } // ctor

  public CancionDTO (int _id, String _artista, String _titulo, String _tipo, int _tamKB, byte[] _audio)
  {
    id = _id;
    artista = _artista;
    titulo = _titulo;
    tipo = _tipo;
    tamKB = _tamKB;
    audio = _audio;
  } // ctor

} // class CancionDTO
